/**
 * Generated by scripts/compiler-build-id.ts. Do not edit by hand.
 *
 * Runtime inputs:
 * - bun.lock
 * - package.json
 * - src/lib/artifacts/source-types.generated.ts
 * - src/lib/artifacts/surface-schema.generated.ts
 * - src/lib/artifacts/surface.ts
 * - src/lib/grammar/labels.ts
 * - src/lib/grammar/types.ts
 * - src/lib/grammar/version.ts
 * - src/lib/surface-edge/build.ts
 * - src/lib/surface-edge/compile.ts
 * - src/lib/surface-edge/emit.ts
 * - src/lib/surface-edge/hints.ts
 * - src/lib/surface-edge/refs.ts
 * - src/lib/surface-edge/resolve.ts
 * - src/lib/surface-edge/spec.ts
 */
export const COMPILER_BUILD_SHA256 =
	"sha256:fb320e32cd7813e1dc8c9c5699f3641e6673ebce7237a430faa54d50f92cfc4b" as const;
